"""Parallel bivariate-tail simulation study for the ``npptcop`` package.

This script keeps the original exact single-family benchmark and adds a new
``patchwork`` benchmark designed to stress nonparametric tail estimators.

Modes
-----
- ``single``: exact copula simulation for one family per cell.
- ``patchwork``: a lower-tail patchwork benchmark with two diagonal tail patches
  inside ``[0, q] x [0, q]`` and a weak background component outside.
- ``both``: run both studies and concatenate the results.

Important note about the patchwork mode
---------------------------------------
The patchwork mode is a *benchmark density on the unit square*, not a fully
analytic copula construction. It is intentionally designed to create two
visibly different lower-tail patches so that nonparametric estimators have a
real local-structure advantage to learn.

The data are generated by mixing three region-specific components:
- background component on the whole square,
- Patch A on the lower triangle of the lower-tail square,
- Patch B on the upper triangle of the lower-tail square.

The true target density in patchwork mode is therefore known by construction,
while the actual estimator inputs are the simulated unit-square samples.
"""

from __future__ import annotations

import argparse
import logging
import math
import multiprocessing
import os
from concurrent.futures import ProcessPoolExecutor, as_completed
from dataclasses import dataclass
from itertools import product
from pathlib import Path
from typing import Literal

import numpy as np
import pandas as pd
import pyvinecopulib as pv
import torch
from torch import Tensor

from npptcop import (
  ParametricTailCopula,
  ProbitTLL,
  TailCopula,
  grid_metrics_density,
  unit_grid,
)

LOG = logging.getLogger("sim_study_biv_tail")

# -----------------------------------------------------------------------------
# Shared setup
# -----------------------------------------------------------------------------

FAMILIES: tuple[str, ...] = ("clayton", "gumbel", "student", "gaussian")
DEFAULT_FAMILIES: tuple[str, ...] = ("clayton", "gumbel", "student")
FAMILY_ROTATION: dict[str, int] = {
  "clayton": 0,
  "gumbel": 180,
  "student": 0,
  "gaussian": 0,
}
PARAMETRIC_MODELS: dict[str, str] = {
  "HR": "husler_reiss",
  "NegLogistic": "neg_logistic",
  "Logistic": "logistic",
  "Dirichlet": "dirichlet",
}
COLUMNS: tuple[str, ...] = (
  "mode",
  "seed",
  "family",
  "tau",
  "tau_a",
  "tau_b",
  "n",
  "k",
  "q",
  "model",
  "target",
  "ISE",
  "IAE",
  "KL",
  "p_hat",
  "p_true",
  "AE",
  "RE",
)


# -----------------------------------------------------------------------------
# Copula helpers
# -----------------------------------------------------------------------------


def q_of_n(n: int) -> float:
  return n ** (-0.5)


def copula_params(family: str, tau: float, nu: int = 4) -> dict[str, float]:
  if family == "clayton":
    return {"theta": 2.0 * tau / (1.0 - tau)}
  if family == "gumbel":
    return {"theta": 1.0 / (1.0 - tau)}
  if family in {"gaussian", "student"}:
    params = {"rho": math.sin(math.pi * tau / 2.0)}
    if family == "student":
      params["nu"] = float(nu)
    return params
  raise ValueError(f"Unknown family: {family}")


def set_bicop(family: str, params: dict[str, float]) -> pv.Bicop:
  if family == "clayton":
    return pv.Bicop(
      family=pv.BicopFamily.clayton,  # type: ignore[attr-defined]
      rotation=0,
      parameters=np.array([[params["theta"]]], dtype=float),
    )
  if family == "gumbel":
    return pv.Bicop(
      family=pv.BicopFamily.gumbel,  # type: ignore[attr-defined]
      rotation=0,
      parameters=np.array([[params["theta"]]], dtype=float),
    )
  if family == "gaussian":
    return pv.Bicop(
      family=pv.BicopFamily.gaussian,  # type: ignore[attr-defined]
      parameters=np.array([[params["rho"]]], dtype=float),
    )
  if family == "student":
    return pv.Bicop(
      family=pv.BicopFamily.student,  # type: ignore[attr-defined]
      parameters=np.array([[params["rho"]], [params["nu"]]], dtype=float),
    )
  raise ValueError(f"Unknown family: {family}")


def sample_bicop(
  n: int, seed: int, family: str, spec: dict[str, float]
) -> np.ndarray:
  bicop = set_bicop(family, copula_params(family, **spec))
  return bicop.simulate(n, seeds=[seed])


def rank_to_pseudo_observations(u: np.ndarray) -> np.ndarray:
  """Optional rank transform (not used in single mode; available for experiments)."""
  n = u.shape[0]
  ranks = np.empty_like(u, dtype=float)
  for j in range(u.shape[1]):
    order = np.argsort(u[:, j], kind="mergesort")
    ranks[order, j] = np.arange(1, n + 1, dtype=float)
  return ranks / (n + 1.0)


# -----------------------------------------------------------------------------
# Patchwork benchmark definitions
# -----------------------------------------------------------------------------

# Fixed families for the two tail patches.
PATCH_A_FAMILY = "clayton"
PATCH_B_FAMILY = "student"
BACKGROUND_FAMILY = "gaussian"
BACKGROUND_TAU = 0.10
PATCH_A_SHARE = 0.15
PATCH_B_SHARE = 0.15
BACKGROUND_SHARE = 1.0 - PATCH_A_SHARE - PATCH_B_SHARE
PATCH_TAU_VALUES: tuple[float, float] = (0.4, 0.8)


@dataclass(frozen=True)
class PatchworkSpec:
  mode: Literal["patchwork"]
  seed: int
  tau_a: float
  tau_b: float
  n: int
  grid_size: int
  eps: float
  min_tail_count: int
  ridge: float
  use_pseudo_observations: bool


# -----------------------------------------------------------------------------
# Job/result containers
# -----------------------------------------------------------------------------


@dataclass(frozen=True)
class SingleComboSpec:
  mode: Literal["single"]
  seed: int
  family: str
  tau: float
  n: int
  nu: int
  grid_size: int
  eps: float
  rotation: int
  min_tail_count: int
  ridge: float


ComboSpec = SingleComboSpec | PatchworkSpec


@dataclass(frozen=True)
class ComboResult:
  spec: ComboSpec
  status: str
  k: int | None
  rows: list[dict[str, object]]


# -----------------------------------------------------------------------------
# Worker init
# -----------------------------------------------------------------------------


def _init_worker() -> None:
  torch.set_default_dtype(torch.float64)
  torch.set_num_threads(1)


# -----------------------------------------------------------------------------
# Geometry helpers
# -----------------------------------------------------------------------------


def _reflect(u: Tensor, rotation: int) -> Tensor:
  if rotation == 90:
    return torch.stack((1.0 - u[:, 0], u[:, 1]), dim=1)
  if rotation == 180:
    return 1.0 - u
  if rotation == 270:
    return torch.stack((u[:, 0], 1.0 - u[:, 1]), dim=1)
  return u


def _corner_count(u: Tensor, q: float, rotation: int) -> int:
  corner = _reflect(u, rotation)
  return int(((corner[:, 0] <= q) & (corner[:, 1] <= q)).sum())


def _corner_mass_single(bicop: pv.Bicop, q: float, rotation: int) -> float:
  def cdf(a: float, b: float) -> float:
    return float(np.asarray(bicop.cdf(np.array([[a, b]])))[0])

  if rotation == 90:
    return q - cdf(1.0 - q, q)
  if rotation == 180:
    return 2.0 * q - 1.0 + cdf(1.0 - q, 1.0 - q)
  if rotation == 270:
    return q - cdf(q, 1.0 - q)
  return cdf(q, q)


def _truth_targets_single(
  bicop: pv.Bicop, u_tail_grid: Tensor, q: float, rotation: int
) -> tuple[Tensor, Tensor, Tensor, float]:
  corner = _reflect(u_tail_grid, rotation)
  c_true = torch.as_tensor(bicop.pdf(corner.numpy()), dtype=torch.float64)
  r_true = q * c_true
  p_true = _corner_mass_single(bicop, q, rotation)
  h_true = (q**2 / p_true) * c_true
  return c_true, r_true, h_true, p_true


# -----------------------------------------------------------------------------
# Patchwork benchmark generation and truth
# -----------------------------------------------------------------------------


def _triangle_transform(sample: np.ndarray, q: float, which: str) -> np.ndarray:
  """Map a [0,1]^2 sample into the lower-left square and then into one triangle.

  ``which == 'A'`` maps to the lower triangle (u2 <= u1).
  ``which == 'B'`` maps to the upper triangle (u2 > u1).
  """
  u = q * sample
  if which == "A":
    return np.sort(u, axis=1)[:, ::-1]
  if which == "B":
    return np.sort(u, axis=1)
  raise ValueError(which)


def sample_patchwork_benchmark(
  n: int,
  seed: int,
  tau_a: float,
  tau_b: float,
  use_pseudo_observations: bool,
) -> np.ndarray:
  """Sample a region-based lower-tail patchwork benchmark.

  The returned sample lives in [0,1]^2. Patch A occupies the lower triangle of
  the lower-tail square, Patch B the upper triangle, and the background fills
  the remaining mass.
  """
  rng = np.random.default_rng(seed)
  labels = rng.choice(
    3,
    size=n,
    p=np.array([BACKGROUND_SHARE, PATCH_A_SHARE, PATCH_B_SHARE], dtype=float),
  )

  u = np.empty((n, 2), dtype=float)

  # Background component over the full square.
  idx_bg = np.where(labels == 0)[0]
  if len(idx_bg) > 0:
    bg = sample_bicop(
      len(idx_bg), seed + 11, BACKGROUND_FAMILY, {"tau": BACKGROUND_TAU}
    )
    u[idx_bg] = bg

  # Patch A: lower triangle of [0, q]^2.
  idx_a = np.where(labels == 1)[0]
  if len(idx_a) > 0:
    a = sample_bicop(len(idx_a), seed + 101, PATCH_A_FAMILY, {"tau": tau_a})
    u[idx_a] = _triangle_transform(a, q=0.10, which="A")

  # Patch B: upper triangle of [0, q]^2.
  idx_b = np.where(labels == 2)[0]
  if len(idx_b) > 0:
    b = sample_bicop(
      len(idx_b), seed + 202, PATCH_B_FAMILY, {"tau": tau_b, "nu": 4}
    )
    u[idx_b] = _triangle_transform(b, q=0.10, which="B")

  if use_pseudo_observations:
    u = rank_to_pseudo_observations(u)

  return u


def _patch_component_density(
  bicop: pv.Bicop,
  u_grid: Tensor,
  q: float,
  triangle: str,
) -> Tensor:
  """Density of a scaled triangle component (approximate but coherent benchmark)."""
  # On the lower-tail square, the component density is the scaled copula density.
  # Sorting into a triangle effectively doubles the density on that triangle.
  u = u_grid.clone()
  if triangle == "A":
    mask = u[:, 1] <= u[:, 0]
  elif triangle == "B":
    mask = u[:, 1] > u[:, 0]
  else:
    raise ValueError(triangle)

  out = torch.zeros(u.shape[0], dtype=torch.float64)
  if mask.any():
    x = u[mask] / q
    out[mask] = (2.0 / (q**2)) * torch.as_tensor(
      bicop.pdf(x.numpy()), dtype=torch.float64
    )
  return out


def _truth_targets_patchwork(
  tau_a: float,
  tau_b: float,
  u_tail_grid: Tensor,
  q: float,
  rotation: int,
) -> tuple[Tensor, Tensor, Tensor, float]:
  """Benchmark truth for the patchwork mode.

  This is the exact density of the benchmark construction used by
  ``sample_patchwork_benchmark``.
  """
  bicop_bg = set_bicop(
    BACKGROUND_FAMILY, copula_params(BACKGROUND_FAMILY, BACKGROUND_TAU)
  )
  bicop_a = set_bicop(PATCH_A_FAMILY, copula_params(PATCH_A_FAMILY, tau_a))
  bicop_b = set_bicop(
    PATCH_B_FAMILY, copula_params(PATCH_B_FAMILY, tau_b, nu=4)
  )

  corner = _reflect(u_tail_grid, rotation)

  c_bg = torch.as_tensor(bicop_bg.pdf(corner.numpy()), dtype=torch.float64)
  c_a = _patch_component_density(bicop_a, corner, q, triangle="A")
  c_b = _patch_component_density(bicop_b, corner, q, triangle="B")

  c_true = BACKGROUND_SHARE * c_bg + PATCH_A_SHARE * c_a + PATCH_B_SHARE * c_b
  r_true = q * c_true

  # Tail mass: background mass in [0,q]^2 plus all of the patch masses.
  def bg_cdf(a: float, b: float) -> float:
    return float(np.asarray(bicop_bg.cdf(np.array([[a, b]])))[0])

  p_bg = bg_cdf(q, q)
  p_true = BACKGROUND_SHARE * p_bg + PATCH_A_SHARE + PATCH_B_SHARE
  h_true = (q**2 / p_true) * c_true
  return c_true, r_true, h_true, p_true


# -----------------------------------------------------------------------------
# Estimator helpers
# -----------------------------------------------------------------------------


def _ordinary_targets(
  u_data: Tensor,
  u_tail_grid: Tensor,
  q: float,
  cell_area_tail: float,
  ridge: float,
  rotation: int,
) -> tuple[Tensor, Tensor, Tensor, float]:
  corner = _reflect(u_tail_grid, rotation)
  c_body = ProbitTLL(ridge=ridge).fit(u_data).evaluate(corner)
  p_body = float(c_body.sum() * cell_area_tail)
  r_body = q * c_body
  h_body = (q**2 / p_body) * c_body
  return c_body, r_body, h_body, p_body


def _metric_rows(
  spec: ComboSpec,
  q: float,
  k: int,
  mode_label: str,
  family_label: str,
  tau_label: float | None,
  tau_a_label: float | None,
  tau_b_label: float | None,
  ests: dict[str, dict[str, Tensor]],
  truths: dict[str, Tensor],
  cell_areas: dict[str, float],
  p_hats: dict[str, float],
  p_true: float,
) -> list[dict[str, object]]:
  base: dict[str, object] = {
    "mode": mode_label,
    "seed": spec.seed,
    "family": family_label,
    "tau": tau_label,
    "tau_a": tau_a_label,
    "tau_b": tau_b_label,
    "n": spec.n,
    "k": k,
    "q": q,
  }
  rows: list[dict[str, object]] = []
  for model, model_ests in ests.items():
    for target, est in model_ests.items():
      metrics = grid_metrics_density(est, truths[target], cell_areas[target])
      rows.append({**base, "model": model, "target": target, **metrics})
  for model, p_hat in p_hats.items():
    rows.append(
      {
        **base,
        "model": model,
        "target": "p",
        "p_hat": p_hat,
        "p_true": p_true,
        "AE": abs(p_hat - p_true),
        "RE": abs(p_hat - p_true) / p_true,
      }
    )
  return rows


# -----------------------------------------------------------------------------
# Simulation kernels
# -----------------------------------------------------------------------------


def _simulate_single(spec: SingleComboSpec) -> ComboResult:
  try:
    params = copula_params(spec.family, spec.tau, spec.nu)
    bicop = set_bicop(spec.family, params)
    u_data = torch.as_tensor(
      bicop.simulate(spec.n, seeds=[spec.seed]), dtype=torch.float64
    )
    q = q_of_n(spec.n)
    k = _corner_count(u_data, q, spec.rotation)
    if k < spec.min_tail_count:
      return ComboResult(
        spec, f"skipped (k={k} < {spec.min_tail_count})", k, []
      )

    grid, cell_area = unit_grid(spec.grid_size, spec.eps)
    u_tail_grid = grid * q
    cell_area_tail = (q**2) * cell_area

    tail = TailCopula(q, rotation=spec.rotation, ridge=spec.ridge).fit(u_data)
    c_true, r_true, h_true, p_true = _truth_targets_single(
      bicop, u_tail_grid, q, spec.rotation
    )
    c_body, r_body, h_body, p_body = _ordinary_targets(
      u_data, u_tail_grid, q, cell_area_tail, spec.ridge, spec.rotation
    )

    ests = {
      "Ordinary": {"r": r_body, "h": h_body, "c": c_body},
      "Tail": {"r": tail.r(grid), "h": tail.h(grid), "c": tail.c(grid)},
    }
    truths = {"r": r_true, "h": h_true, "c": c_true}
    cell_areas = {"r": cell_area, "h": cell_area, "c": cell_area_tail}
    p_hats = {"Ordinary": p_body, "Tail": tail.fit_.p}

    for model, family in PARAMETRIC_MODELS.items():
      try:
        par_est = ParametricTailCopula(family, q, rotation=spec.rotation).fit(
          u_data
        )
      except Exception:  # noqa: BLE001
        continue
      ests[model] = {
        "r": par_est.r(grid),
        "h": par_est.h(grid),
        "c": par_est.c(grid),
      }
      p_hats[model] = par_est.fit_.p

    rows = _metric_rows(
      spec,
      q,
      k,
      mode_label="single",
      family_label=spec.family,
      tau_label=spec.tau,
      tau_a_label=None,
      tau_b_label=None,
      ests=ests,
      truths=truths,
      cell_areas=cell_areas,
      p_hats=p_hats,
      p_true=p_true,
    )
    return ComboResult(spec, "ok", k, rows)
  except torch.linalg.LinAlgError:
    return ComboResult(spec, "skipped (singular bandwidth)", None, [])
  except Exception as exc:  # noqa: BLE001
    return ComboResult(spec, f"error: {exc!r}", None, [])


def _simulate_patchwork(spec: PatchworkSpec) -> ComboResult:
  try:
    q = q_of_n(spec.n)
    u_raw = sample_patchwork_benchmark(
      n=spec.n,
      seed=spec.seed,
      tau_a=spec.tau_a,
      tau_b=spec.tau_b,
      use_pseudo_observations=spec.use_pseudo_observations,
    )
    u = torch.as_tensor(u_raw, dtype=torch.float64)

    k = _corner_count(u, q, rotation=0)
    if k < spec.min_tail_count:
      return ComboResult(
        spec, f"skipped (k={k} < {spec.min_tail_count})", k, []
      )

    grid, cell_area = unit_grid(spec.grid_size, spec.eps)
    u_tail_grid = grid * q
    cell_area_tail = (q**2) * cell_area

    tail = TailCopula(q, rotation=0, ridge=spec.ridge).fit(u)
    c_true, r_true, h_true, p_true = _truth_targets_patchwork(
      spec.tau_a, spec.tau_b, u_tail_grid, q, rotation=0
    )
    c_body, r_body, h_body, p_body = _ordinary_targets(
      u, u_tail_grid, q, cell_area_tail, spec.ridge, rotation=0
    )

    ests = {
      "Ordinary": {"r": r_body, "h": h_body, "c": c_body},
      "Tail": {"r": tail.r(grid), "h": tail.h(grid), "c": tail.c(grid)},
    }
    truths = {"r": r_true, "h": h_true, "c": c_true}
    cell_areas = {"r": cell_area, "h": cell_area, "c": cell_area_tail}
    p_hats = {"Ordinary": p_body, "Tail": tail.fit_.p}

    for model, family in PARAMETRIC_MODELS.items():
      try:
        par_est = ParametricTailCopula(family, q, rotation=0).fit(u)
      except Exception:  # noqa: BLE001
        continue
      ests[model] = {
        "r": par_est.r(grid),
        "h": par_est.h(grid),
        "c": par_est.c(grid),
      }
      p_hats[model] = par_est.fit_.p

    rows = _metric_rows(
      spec,
      q,
      k,
      mode_label="patchwork",
      family_label="",
      tau_label=None,
      tau_a_label=spec.tau_a,
      tau_b_label=spec.tau_b,
      ests=ests,
      truths=truths,
      cell_areas=cell_areas,
      p_hats=p_hats,
      p_true=p_true,
    )
    return ComboResult(spec, "ok", k, rows)
  except torch.linalg.LinAlgError:
    return ComboResult(spec, "skipped (singular bandwidth)", None, [])
  except Exception as exc:  # noqa: BLE001
    return ComboResult(spec, f"error: {exc!r}", None, [])


def run_combo(spec: ComboSpec) -> ComboResult:
  if spec.mode == "single":
    assert isinstance(spec, SingleComboSpec)
    return _simulate_single(spec)
  assert isinstance(spec, PatchworkSpec)
  return _simulate_patchwork(spec)


# -----------------------------------------------------------------------------
# CLI / orchestration
# -----------------------------------------------------------------------------


def build_parser() -> argparse.ArgumentParser:
  parser = argparse.ArgumentParser(
    description="Parallel bivariate-tail simulation study for npptcop."
  )
  parser.add_argument(
    "--mode",
    choices=["single", "patchwork", "both"],
    default="single",
    help="Run the exact single-family study, the patchwork benchmark, or both.",
  )
  parser.add_argument(
    "--families", nargs="+", choices=FAMILIES, default=list(DEFAULT_FAMILIES)
  )
  parser.add_argument("--taus", nargs="+", type=float, default=[0.4, 0.8])
  parser.add_argument(
    "--ns",
    nargs="+",
    type=int,
    default=[200, 500, 1000, 2000, 5000, 10000, 20000, 50000],
  )
  parser.add_argument("--seeds", nargs="+", type=int, default=list(range(30)))
  parser.add_argument("--nu", type=int, default=4)
  parser.add_argument("--grid-size", type=int, default=100)
  parser.add_argument("--eps", type=float, default=1e-4)
  parser.add_argument("--min-tail-count", type=int, default=5)
  parser.add_argument("--ridge", type=float, default=1e-6)
  parser.add_argument(
    "--use-pseudo-observations",
    action="store_true",
    help="Apply the rank transform before fitting in patchwork mode.",
  )
  parser.add_argument(
    "--output",
    type=Path,
    default=Path("results/sim_study_biv_tail_patchwork.csv"),
  )
  parser.add_argument("--workers", type=int, default=None)
  parser.add_argument(
    "--log-level",
    choices=["DEBUG", "INFO", "WARNING", "ERROR"],
    default="INFO",
  )
  parser.add_argument("--dry-run", action="store_true")
  return parser


def enumerate_single_combos(args: argparse.Namespace) -> list[SingleComboSpec]:
  return [
    SingleComboSpec(
      mode="single",
      seed=seed,
      family=family,
      tau=tau,
      n=n,
      nu=args.nu,
      grid_size=args.grid_size,
      eps=args.eps,
      rotation=FAMILY_ROTATION[family],
      min_tail_count=args.min_tail_count,
      ridge=args.ridge,
    )
    for seed, family, tau, n in product(
      args.seeds, args.families, args.taus, args.ns
    )
  ]


def enumerate_patchwork_combos(args: argparse.Namespace) -> list[PatchworkSpec]:
  return [
    PatchworkSpec(
      mode="patchwork",
      seed=seed,
      tau_a=tau_a,
      tau_b=tau_b,
      n=n,
      grid_size=args.grid_size,
      eps=args.eps,
      min_tail_count=args.min_tail_count,
      ridge=args.ridge,
      use_pseudo_observations=args.use_pseudo_observations,
    )
    for seed, tau_a, tau_b, n in product(
      args.seeds, PATCH_TAU_VALUES, PATCH_TAU_VALUES, args.ns
    )
  ]


def enumerate_combos(args: argparse.Namespace) -> list[ComboSpec]:
  specs: list[ComboSpec] = []
  if args.mode in {"single", "both"}:
    specs.extend(enumerate_single_combos(args))
  if args.mode in {"patchwork", "both"}:
    specs.extend(enumerate_patchwork_combos(args))
  return specs


def run_study(specs: list[ComboSpec], workers: int) -> list[ComboResult]:
  ctx = multiprocessing.get_context("spawn")
  results: list[ComboResult] = []
  total = len(specs)
  with ProcessPoolExecutor(
    max_workers=workers, mp_context=ctx, initializer=_init_worker
  ) as executor:
    futures = {executor.submit(run_combo, spec): spec for spec in specs}
    for i, future in enumerate(as_completed(futures), start=1):
      result = future.result()
      spec = result.spec
      k_str = "-" if result.k is None else str(result.k)
      if spec.mode == "single":
        assert isinstance(spec, SingleComboSpec)
        name = spec.family
        extra = f"tau={spec.tau:.2f}"
      else:
        assert isinstance(spec, PatchworkSpec)
        name = f"{spec.tau_a:.1f}/{spec.tau_b:.1f}"
        extra = "patchwork"
      LOG.info(
        "[%d/%d] %-12s | %s | n=%5d | seed=%d -> k=%s, %s",
        i,
        total,
        name,
        extra,
        spec.n,
        spec.seed,
        k_str,
        result.status,
      )
      results.append(result)
  return results


def results_to_frame(results: list[ComboResult]) -> pd.DataFrame:
  rows = [row for result in results for row in result.rows]
  return pd.DataFrame(rows, columns=list(COLUMNS))


def main() -> None:
  args = build_parser().parse_args()
  logging.basicConfig(
    level=args.log_level,
    format="%(asctime)s %(levelname)-7s %(name)s | %(message)s",
    datefmt="%H:%M:%S",
  )
  os.environ.setdefault("OMP_NUM_THREADS", "1")
  os.environ.setdefault("MKL_NUM_THREADS", "1")

  specs = enumerate_combos(args)
  workers = args.workers or min(os.cpu_count() or 1, 8)
  LOG.info("%d combos | %d workers -> %s", len(specs), workers, args.output)
  if args.dry_run:
    LOG.info("dry run: no computation or output")
    return

  results = run_study(specs, workers)
  n_ok = sum(1 for r in results if r.status == "ok")
  LOG.info("done: %d/%d combos produced rows", n_ok, len(results))

  frame = results_to_frame(results)
  args.output.parent.mkdir(parents=True, exist_ok=True)
  frame.to_csv(args.output, index=False)
  LOG.info("wrote %d rows -> %s", len(frame), args.output)


if __name__ == "__main__":
  main()
